# Generated by scripts/install_cardinal_mac.sh on Fri Sep  4 16:49:08 CDT 2026
# Source this before building or running Cardinal:
#   source /Users/chenghau.yang/cardinal/cardinal_env.sh

conda activate moose

export CARDINAL_DIR="/Users/chenghau.yang/cardinal"
export ENABLE_NEK=false
export ENABLE_OPENMC=true
export HDF5_ROOT="${CONDA_PREFIX}"

# macOS uses DYLD_LIBRARY_PATH; LD_LIBRARY_PATH is kept for portability.
export DYLD_LIBRARY_PATH="${CONDA_PREFIX}/lib${DYLD_LIBRARY_PATH:+:${DYLD_LIBRARY_PATH}}"
export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

export MOOSE_JOBS=8
export LIBMESH_JOBS=8
export JOBS=8

export OPENMC_CROSS_SECTIONS="/Users/chenghau.yang/cross_sections/endfb-vii.1-hdf5/cross_sections.xml"

export PATH="/Users/chenghau.yang/cardinal:${PATH}"
