# Generated by scripts/install_cardinal_mac.sh on Fri Sep  4 16:49:08 CDT 2026
# Source this before building or running Cardinal:
#   source /Users/chenghau.yang/Documents/Package/cardinal/cardinal_env.sh

conda activate moose

if [ -n "${BASH_VERSION:-}" ]; then
  _cardinal_env_file="${BASH_SOURCE[0]}"
elif [ -n "${ZSH_VERSION:-}" ]; then
  _cardinal_env_file="${(%):-%x}"
else
  _cardinal_env_file="$0"
fi
export CARDINAL_DIR="$(cd -- "$(dirname -- "${_cardinal_env_file}")" && pwd)"
unset _cardinal_env_file
export ENABLE_NEK=true
export NEKRS_HOME="${CARDINAL_DIR}/install"
export ENABLE_OPENMC=true
export HDF5_ROOT="${CONDA_PREFIX}"

# Kept for portability when this environment is used on Linux. Do not set
# DYLD_LIBRARY_PATH globally on macOS; it can break non-Conda executables.
export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

export MOOSE_JOBS=8
export LIBMESH_JOBS=8
export JOBS=8

export OPENMC_CROSS_SECTIONS="/Users/chenghau.yang/cross_sections/endfb-vii.1-hdf5/cross_sections.xml"

export PATH="${CARDINAL_DIR}:${PATH}"
